-- AlterTable
ALTER TABLE "Coupon" ADD COLUMN     "end" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "start" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "used" INTEGER NOT NULL DEFAULT 0;
